# Lesson 10 demo: Pandas

## 1. Set up

Install with:

```text
pip install pandas
```

In [1]:
import pandas as pd
print(f'Pandas version {pd.__version__}')

Pandas version 1.5.3

## 1. Series: one-dimensional data

### 1.1. Create a series

In [2]:
my_series = pd.Series([20, 30, 40, 50])
print(my_series)

0    20
1    30
2    40
3    50
dtype: int64

In [3]:
type(my_series)

pandas.core.series.Series

In [4]:
day = ['Mon', 'Tues', 'Wed', 'Thurs']
print(day)

['Mon', 'Tues', 'Wed', 'Thurs']

In [5]:
my_indexed_series = pd.Series([20, 30, 40, 50], index=day)
print(my_indexed_series)

Mon      20
Tues     30
Wed      40
Thurs    50
dtype: int64

### 1.2. Indexing series

In [6]:
print(my_indexed_series['Wed'])

40

In [8]:
print(my_series.iloc[1])

30

### 2.3. Series operations

In [9]:
print(my_series.max())

50

In [10]:
print(my_series.mean())

35.0

## 2. DataFrame: two-deimensional data

### 2.1. Creating dataframes

In [43]:
data = {
    'name': ['Alice', 'Bob', 'Laura', 'George'],
    'age': [25, 30, 35, 40],
    'city': ['New York', 'Paris', 'London', 'Chicago'],
    'salary': [50000, 60000, 70000, 80000]
}

type(data)

dict

In [44]:
print(data)

{'name': ['Alice', 'Bob', 'Laura', 'George'], 'age': [25, 30, 35, 40], 'city': ['New York', 'Paris', 'London', 'Chicago'], 'salary': [50000, 60000, 70000, 80000]}

In [45]:
df = pd.DataFrame(data)
df

     name  age      city  salary
0   Alice   25  New York   50000
1     Bob   30     Paris   60000
2   Laura   35    London   70000
3  George   40   Chicago   80000

### 2.2. Setting the index

In [46]:
new_index = ['a', 'b', 'c', 'd']
df.set_index(pd.Index(new_index), inplace=True)

In [47]:
df['index_col'] = new_index

In [48]:
df

     name  age      city  salary index_col
a   Alice   25  New York   50000         a
b     Bob   30     Paris   60000         b
c   Laura   35    London   70000         c
d  George   40   Chicago   80000         d

In [50]:
df.drop('index_col', axis=1, inplace=True)
df

     name  age      city  salary
a   Alice   25  New York   50000
b     Bob   30     Paris   60000
c   Laura   35    London   70000
d  George   40   Chicago   80000

In [51]:
df.reset_index(inplace=True, drop=True)
df

     name  age      city  salary
0   Alice   25  New York   50000
1     Bob   30     Paris   60000
2   Laura   35    London   70000
3  George   40   Chicago   80000

### 2.3. Getting and setting column names

In [52]:
col_names = df.columns

In [53]:
print(col_names)

Index(['name', 'age', 'city', 'salary'], dtype='object')

In [54]:
rename_dict = {'city': 'location'}

In [55]:
df.rename(columns=rename_dict, inplace=True)
df

     name  age  location  salary
0   Alice   25  New York   50000
1     Bob   30     Paris   60000
2   Laura   35    London   70000
3  George   40   Chicago   80000

In [61]:
df.column = pd.Index(['Name', 'Age', 'City', 'Salary'])
df

     name  age  location  salary
0   Alice   25  New York   50000
1     Bob   30     Paris   60000
2   Laura   35    London   70000
3  George   40   Chicago   80000

### 2.4. Getting information about dataframe

In [62]:
df.head(2)

    name  age  location  salary
0  Alice   25  New York   50000
1    Bob   30     Paris   60000

In [63]:
df.tail(3)

     name  age location  salary
1     Bob   30    Paris   60000
2   Laura   35   London   70000
3  George   40  Chicago   80000

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      4 non-null      object
 1   age       4 non-null      int64
 2   location  4 non-null      object
 3   salary    4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 256.0+ bytes

In [65]:
df.describe()

             age        salary
count   4.000000      4.000000
mean   32.500000  65000.000000
std     6.454972  12909.944487
min    25.000000  50000.000000
25%    28.750000  57500.000000
50%    32.500000  65000.000000
75%    36.250000  72500.000000
max    40.000000  80000.000000